In [9]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
import matplotlib.pyplot as plt

In [10]:
drive_base_path = "../"
path_to_images = drive_base_path + "dataset/ISIC2018_Balanced_Training_Input/"

In [30]:
train_datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

In [31]:
classes = ['mel', 'nv', 'bcc', 'akiec', 'bkl', 'df', 'vasc']
train_generator = train_datagen.flow_from_directory(
                    directory=path_to_images,
                    target_size=(224, 224),
                    batch_size=32,
                    classes=classes,
                    shuffle=True)

Found 16639 images belonging to 7 classes.


In [32]:
train_generator.class_indices

{'mel': 0, 'nv': 1, 'bcc': 2, 'akiec': 3, 'bkl': 4, 'df': 5, 'vasc': 6}

In [33]:
x, y = next(train_generator)

In [34]:
print(x[0].shape)

(256, 256, 3)


In [36]:
print(x[0])

[[[162.0451  165.03008 241.98497]
  [164.6653  166.77687 241.11157]
  [158.90535 164.71451 237.19084]
  ...
  [159.01503 156.96992 240.96992]
  [154.70818 155.28326 237.56654]
  [157.65881 153.53647 238.46353]]

 [[162.0451  165.03008 241.98497]
  [164.6653  166.77687 241.11157]
  [158.90535 164.71451 237.19084]
  ...
  [159.01503 156.96992 240.96992]
  [154.70818 155.28326 237.56654]
  [157.65881 153.53647 238.46353]]

 [[162.0451  165.03008 241.98497]
  [164.6653  166.77687 241.11157]
  [158.90535 164.71451 237.19084]
  ...
  [159.01503 156.96992 240.96992]
  [154.70818 155.28326 237.56654]
  [157.65881 153.53647 238.46353]]

 ...

 [[122.07517 149.07516 216.07516]
  [126.44217 153.44217 220.44217]
  [128.52367 152.47633 219.47633]
  ...
  [135.96992 149.93987 222.9549 ]
  [141.15019 155.15019 226.43346]
  [140.53647 153.8047  224.07295]]

 [[122.07517 149.07516 216.07516]
  [126.44217 153.44217 220.44217]
  [128.52367 152.47633 219.47633]
  ...
  [135.96992 149.93987 222.9549 ]
  [1

In [19]:
print(y[0])

[1. 0. 0. 0. 0. 0. 0.]
